# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uploadshapefile_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uploadshapefileDialogBase(object):
    def setupUi(self, uploadshapefileDialogBase):
        uploadshapefileDialogBase.setObjectName("uploadshapefileDialogBase")
        uploadshapefileDialogBase.resize(596, 511)
        self.button_box = QtWidgets.QDialogButtonBox(uploadshapefileDialogBase)
        self.button_box.setGeometry(QtCore.QRect(230, 450, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pushButton = QtWidgets.QPushButton(uploadshapefileDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(30, 140, 531, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(uploadshapefileDialogBase)
        self.lineEdit.setGeometry(QtCore.QRect(30, 90, 531, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(uploadshapefileDialogBase)
        self.label.setGeometry(QtCore.QRect(40, 10, 101, 61))
        self.label.setMinimumSize(QtCore.QSize(0, 34))
        self.label.setObjectName("label")

        self.retranslateUi(uploadshapefileDialogBase)
        self.button_box.accepted.connect(uploadshapefileDialogBase.accept)
        self.button_box.rejected.connect(uploadshapefileDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(uploadshapefileDialogBase)

    def retranslateUi(self, uploadshapefileDialogBase):
        _translate = QtCore.QCoreApplication.translate
        uploadshapefileDialogBase.setWindowTitle(_translate("uploadshapefileDialogBase", "uploadshapefile"))
        self.pushButton.setText(_translate("uploadshapefileDialogBase", "Load"))
        self.label.setText(_translate("uploadshapefileDialogBase", "Upload Shapefile"))
